### ISSUE TITLE
Weird inconsistencies with device name spacing, case, etc

### ISSUE THREAD

**Issue by corcoran** [jaredrummler/AndroidDeviceNames#7]
This is pretty self explanatory and I'm more curious how it happens in the first place (typos, etc).

I'll give two [recent] examples:
1a) SM-T818V (Samsung Galaxy TabS2 9.7)
1b) SM-T818W (Samsung Galaxy Tab S2 9.7)

There's a space missing between Tab and S2 on the 818V.

2a) SM-P580X (Samsung Galaxy TabA Plus10.1)
2b) SM-P583 (Samsung Galaxy TabA Plus 10.1)

Again, a space is missing.

There are a number of other minor issues, like case sensitivity and such but I'm mostly just curious how it's happening in the first place. Hopefully this isn't coming across as disrespectful, I really appreciate the work done to maintain this library!

**Comment by jaredrummler** [comment]
The library is easy to maintain because it is pulling the device info from Google Play's supported device list here: https://support.google.com/googleplay/answer/1727131?hl=en

Any typo exists because it is also a typo in Google's maintained device list. A pull request to fix a typo in any JSON file might be overridden when updating the list.

**Comment by corcoran** [comment]
Gotcha, thanks for the explanation Jared!
